import React from "react";
const Service = () => {
    return (
        <>
            <h1>Service</h1>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>

            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
            <div>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quidem fugit enim quae quia distinctio minus soluta recusandae laborum facere nulla voluptatum voluptas unde velit laudantium esse tenetur, natus, eius sed alias aliquid magni quaerat! Eaque fugit incidunt, adipisci mollitia impedit, atque sapiente perspiciatis sed voluptatibus nam architecto magnam ipsum magni pariatur facilis officiis repellendus provident sint esse nisi laudantium ea expedita! Assumenda explicabo provident quaerat animi debitis corrupti dicta modi libero delectus! Sunt accusantium earum, explicabo illo ad error nemo maxime officiis architecto asperiores perferendis dolores rem labore sint nihil, quasi dignissimos maiores numquam necessitatibus blanditiis voluptate perspiciatis, ducimus doloremque.
            </div>
            <br/>
        </>
    );
}
export default Service;